"""Fun pligon...for userbot
\nCode by @veryhelpful
type `.evilmsg` and to see the fun.
"""
import random, re
from REBELBOT.utils import admin_cmd
import asyncio
from telethon import events

@borg.on(admin_cmd(pattern="hmsg ?(.*)"))
async def _(event):
     if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await event.edit(".\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")#by @VERYHELPFUL
        await asyncio.sleep(0.1)
        await event.edit(".\n\n.")#CREADIT kraken
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")#if editing thhen add creadit 
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")#copy paster without creadit r madharchod randi ke bache diont copy
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.2)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.2)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.5)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        
        await event.edit(".\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")#by @VERYHELPFUL
        await asyncio.sleep(0.1)
        await event.edit(".\n\n.")#CREADIT kraken
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")#if editing thhen add creadit 
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")#copy paster without creadit r madharchod randi ke bache diont copy
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.2)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.2)
        await event.edit(".\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.5)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.2)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.2)
        await event.edit(".\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.5)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.5)
        await event.edit(".\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.5)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")    
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        
        await event.edit(".\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")    
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        
        await event.edit(".\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")    
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        
        await event.edit(".\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")    
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)        
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")    
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n.")
        await asyncio.sleep(0.1)
        await event.edit(".")
      
      
       
